//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPPamari.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advisor
    {
        public Advisor()
        {
            this.ApplicationUsers = new HashSet<ApplicationUser>();
        }
    
        public int AdvisorID { get; set; }
        public string Name { get; set; }
        public string EMailAddress { get; set; }
    
        public virtual ICollection<ApplicationUser> ApplicationUsers { get; set; }
    }
}
