
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CAPPamari.Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CAPPReport
{

    public CAPPReport()
    {

        this.RequirementSets = new HashSet<RequirementSet>();

    }


    public int ReportID { get; set; }

    public string UserName { get; set; }

    public string Name { get; set; }



    public virtual ApplicationUser ApplicationUser { get; set; }

    public virtual ICollection<RequirementSet> RequirementSets { get; set; }

}

}
