//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPPamari.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelRequirement
    {
        public LevelRequirement()
        {
            this.LevelRequirementDepartments = new HashSet<LevelRequirementDepartment>();
            this.RequirementSets = new HashSet<RequirementSet>();
        }
    
        public int LevelRequirementID { get; set; }
        public string MinimumLevel { get; set; }
        public int CreditsNeeded { get; set; }
    
        public virtual ICollection<LevelRequirementDepartment> LevelRequirementDepartments { get; set; }
        public virtual ICollection<RequirementSet> RequirementSets { get; set; }
    }
}
