
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CAPPamari.Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LevelLimitRSR
{

    public LevelLimitRSR()
    {

        this.RequirementSets = new HashSet<RequirementSet>();

    }


    public int LevelLimitRSRID { get; set; }

    public string CourseLevel { get; set; }

    public int UpperLimit { get; set; }



    public virtual ICollection<RequirementSet> RequirementSets { get; set; }

}

}
