
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CAPPamari.Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class RequirementSet
{

    public RequirementSet()
    {

        this.CommRequirementDepartments = new HashSet<CommRequirementDepartment>();

        this.Courses = new HashSet<Course>();

        this.DepartmentRSRs = new HashSet<DepartmentRSR>();

        this.ExclusionRequirements = new HashSet<ExclusionRequirement>();

        this.LevelLimitRSRs = new HashSet<LevelLimitRSR>();

        this.LevelRequirements = new HashSet<LevelRequirement>();

        this.SingleRequirements = new HashSet<SingleRequirement>();

    }


    public int RequirementSetID { get; set; }

    public string Credits { get; set; }

    public string PassNCCredits { get; set; }

    public string Name { get; set; }

    public int CAPPReportID { get; set; }

    public bool DepthRSR { get; set; }

    public string Description { get; set; }



    public virtual CAPPReport CAPPReport { get; set; }

    public virtual ICollection<CommRequirementDepartment> CommRequirementDepartments { get; set; }

    public virtual ICollection<Course> Courses { get; set; }

    public virtual ICollection<DepartmentRSR> DepartmentRSRs { get; set; }

    public virtual ICollection<ExclusionRequirement> ExclusionRequirements { get; set; }

    public virtual ICollection<LevelLimitRSR> LevelLimitRSRs { get; set; }

    public virtual ICollection<LevelRequirement> LevelRequirements { get; set; }

    public virtual ICollection<SingleRequirement> SingleRequirements { get; set; }

}

}
