//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPPamari.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequirementSet
    {
        public RequirementSet()
        {
            this.Courses = new HashSet<Course>();
            this.CAPPReports = new HashSet<CAPPReport>();
        }
    
        public int RequirementSetID { get; set; }
        public string Credits { get; set; }
        public string PassNCCredits { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<CAPPReport> CAPPReports { get; set; }
    }
}
