
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CAPPamari.Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Requirement
{

    public Requirement()
    {

        this.CAPPReports = new HashSet<CAPPReport>();

        this.CourseFulfillments = new HashSet<CourseFulfillment>();

        this.RequirementSets = new HashSet<RequirementSet>();

        this.RequirementSets1 = new HashSet<RequirementSet>();

    }


    public int RequirementID { get; set; }

    public int CreditsNeeded { get; set; }

    public bool CommunicationIntensive { get; set; }

    public bool Exclusion { get; set; }

    public int PassNoCreditCreditsAllowed { get; set; }



    public virtual ICollection<CAPPReport> CAPPReports { get; set; }

    public virtual ICollection<CourseFulfillment> CourseFulfillments { get; set; }

    public virtual ICollection<RequirementSet> RequirementSets { get; set; }

    public virtual ICollection<RequirementSet> RequirementSets1 { get; set; }

}

}
